apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - id: TMF632
      name: party-management-api
      port: 8080
      required: true
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources:
      - PartyRole:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - id: TMF672
      name: user-role-permission-management-api
      port: 8080
      required: true
      resources:
      - permission:
        - GET
        - GET /id
      - userRole:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - id: TMF670
      name: payment-method-management-api
      port: 8080
      required: false
      resources:
      - paymentMethod:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF670_Payment_Method/4.0.0/swagger/TMF670_Payment_Method_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    - id: TMF676
      name: payment-management-api
      port: 8080
      required: false
      resources:
      - payment:
        - GET
        - GET /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF676_Payment/4.0.0/swagger/TMF676_Payment_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    exposedAPIs:
    - id: TMF666
      name: account-management-api
      port: 8080
      required: true
      resources:
      - BillingAccount:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - BillingCycleSpecification:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - BillFormat:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      - BillPresentationMedia:
        - GET
        - GET /id
        - POST
        - PATCH /id
        - DELETE /id
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF666_Account/4.0.0/swagger/TMF666_Account_Management_API_v4.0.0_swagger.json
      version: v4.0.0
    publishedEvents:
    - apitype: openapi
      implementation: /{{.Release.Name}}-accmngt
      name: AccountManagement
      port: 80
      resources:
      - billingAccountAttributeValueChangeEvent
      - billingAccountStateChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      name: PartyRoleManagement
      port: 80
      resources:
      - partyRoleCreateEvent
      - partyRoleAttributeValueChangeEvent
      - partyRoleStateChangeEvent
      - partyRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    - apitype: openapi
      name: UserRolePermissionManagement
      port: 80
      resources:
      - permissionCreateEvent
      - permissionAttributeValueChangeEvent
      - permissionStateChangeEvent
      - permissionDeleteEvent
      - userRoleCreateEvent
      - userRoleAttributeValueChangeEvent
      - userRoleStateChangeEvent
      - userRoleDeleteEvent
      specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
  description: The billing account management component aims to provide all the needed
    functionalities to create, configure and modify billing accounts. BAM component
    has the goal to support and handle the following capabilities/ functionalities.
    Set-up/ creation of Billing account. Associate payment plan(s). Associate payment
    method(s) - optional. Account taxes/ fees exception management. Define account
    associations. Provide account balance details. Set-up Billing contacts. Set-up
    Billing preferences (e.g., bill cycle frequency, invoice media type, invoice template
    option, etc.)
  functionalBlock: PartyManagement
  id: TMFC024
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: BillingAccountManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: 2024-04-16 00:00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    dependentAPIs: []
    exposedAPIs:
    - id: TMF669
      name: party-role-management-api
      port: 8080
      required: true
      resources: []
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
      version: v4.0.0
  status: specified
  version: 2.0.0
