---
# Source: tmfc009-servicequalificationmanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc009-servicequalificationmanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-service-qualification-management-api'
spec:
  ports:
  - name: tcp-release-name-service
    port: 8080
    targetPort: 'release-name-service'
  selector:
    impl: 'release-name-service-qualification-management-api'
---
# Source: tmfc009-servicequalificationmanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-partyrole-management-api'
spec:
  ports:
  - name: tcp-release-name-partyro
    port: 8080
    targetPort: 'release-name-partyro'
  selector:
    impl: 'release-name-partyrole-management-api'
---
# Source: tmfc009-servicequalificationmanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc009-servicequalificationmanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-service-qualification-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-service-qualification-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc009-servicequalificationmanagement'
        impl: 'release-name-service-qualification-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc009-servicequalificationmanagement'
        image: 'tmforumorg/tmfc009-tmf645-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-service-qualification-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-service'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc009-servicequalificationmanagement/tmf-api/serviceQualificationManagement/v4
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc009-servicequalificationmanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-partyrole-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-partyrole-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc009-servicequalificationmanagement'
        impl: 'release-name-partyrole-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc009-servicequalificationmanagement'
        image: 'tmforumorg/tmfc009-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-partyrole-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-partyro'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc009-servicequalificationmanagement/tmf-api/partyRoleManagement/v4
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc009-servicequalificationmanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc009-servicequalificationmanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc009-servicequalificationmanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc009-servicequalificationmanagement/templates/Job-0.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-roleinitialization'
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        impl: 'release-name-roleinitialization'
    spec:
      containers:
      - env:
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'tmfc009-servicequalificationmanagement'
        - name: PARTY_ROLE_SVC_NAME
          value: 'release-name-partyrole-management-api'
        image: tmforumorg/partyroleinitializer:latest
        imagePullPolicy: Always
        name: roleinitialization
      restartPolicy: OnFailure
---
# Source: tmfc009-servicequalificationmanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc009-servicequalificationmanagement'
  name: 'release-name-tmfc009-servicequalificationmanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: service-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: service-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: resource-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: geographic-address-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: geographic-site-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: user-role-permission-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-service-qualification-management-api'
      name: service-qualification-management-api
      path: /release-name-tmfc009-servicequalificationmanagement/tmf-api/serviceQualificationManagement/v4
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF645_Service_Qualification/4.0.0/swagger/TMF645_Service_Qualification_Management_API_v4.0.0_swagger.json
  description: Service Qualification component is responsible for checking and validating
    the availability of a service according to specified and configured business rules.
    It must identify at least one technical solution (RFSspec) available to deliver
    the service (CFSspec) and check the availability of all the resources types involved
    in this technical solution. No resources are allocated during Service Qualification.
    Service Qualification component has functionality that include checking service
    feasibility status and publishing or reporting service qualification result, but
    also calculated service delivery due date and identified need of an appointment
    at the customer site. Service Qualification can also be in charge of the cost
    calculation of the technical solution identified, when it cannot be determined
    at catalog design time (complex B2B services). This information will be used as
    an input to price calculation.
  functionalBlock: Production
  id: TMFC009
  maintainers:
  - email: Anastasios.sarantis@cityfibre.com
    name: Tassos Sarantis
  name: ServiceQualificationManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: Anastasios.sarantis@cityfibre.com
    name: Tassos Sarantis
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-partyrole-management-api'
      name: partyrole-management-api
      path: /release-name-tmfc009-servicequalificationmanagement/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.1
