---
# Source: tmfc046-workforcemanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc046-workforcemanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-appointment-management-api'
spec:
  ports:
  - name: tcp-release-name-appoint
    port: 8080
    targetPort: 'release-name-appoint'
  selector:
    impl: 'release-name-appointment-management-api'
---
# Source: tmfc046-workforcemanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-partyrole-management-api'
spec:
  ports:
  - name: tcp-release-name-partyro
    port: 8080
    targetPort: 'release-name-partyro'
  selector:
    impl: 'release-name-partyrole-management-api'
---
# Source: tmfc046-workforcemanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc046-workforcemanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-appointment-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-appointment-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc046-workforcemanagement'
        impl: 'release-name-appointment-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc046-workforcemanagement'
        image: 'tmforumorg/tmfc046-tmf646-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-appointment-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-appoint'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc046-workforcemanagement/tmf-api/appointment/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc046-workforcemanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-partyrole-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-partyrole-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc046-workforcemanagement'
        impl: 'release-name-partyrole-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc046-workforcemanagement'
        image: 'tmforumorg/tmfc046-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-partyrole-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-partyro'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc046-workforcemanagement/tmf-api/partyRoleManagement/v4
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc046-workforcemanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc046-workforcemanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc046-workforcemanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc046-workforcemanagement/templates/Job-0.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-roleinitialization'
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        impl: 'release-name-roleinitialization'
    spec:
      containers:
      - env:
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'tmfc046-workforcemanagement'
        - name: PARTY_ROLE_SVC_NAME
          value: 'release-name-partyrole-management-api'
        image: tmforumorg/partyroleinitializer:latest
        imagePullPolicy: Always
        name: roleinitialization
      restartPolicy: OnFailure
---
# Source: tmfc046-workforcemanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc046-workforcemanagement'
  name: 'release-name-tmfc046-workforcemanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: user-role-permission-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-appointment-management-api'
      name: appointment-management-api
      path: /release-name-tmfc046-workforcemanagement/tmf-api/appointment/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF646_Appointment/4.0.0/swagger/TMF646_Appointment_Management_API_v4.0.0_swagger.json
  description: Workforce Management provides capabilities to describe teams, organizations,
    skills and availability of sales / technical experts. It provides the ability
    in reserving time slots to carry out assigned task (internal or customer facing).
    It allows the reservation (and their updates / reschedule) of appointments and
    interventions. option, etc.)
  functionalBlock: Production
  id: TMFC046
  maintainers:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  name: WorkforceManagement
  owners:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-partyrole-management-api'
      name: partyrole-management-api
      path: /release-name-tmfc046-workforcemanagement/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.0.0
