---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-partyrole-management-api'
spec:
  ports:
  - name: tcp-release-name-partyro
    port: 8080
    targetPort: 'release-name-partyro'
  selector:
    impl: 'release-name-partyrole-management-api'
---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-partyrole-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-partyrole-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
        impl: 'release-name-partyrole-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
        image: 'tmforumorg/tmfc003-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-partyrole-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-partyro'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc003-productorderdeliveryorchestrationandmanagement/tmf-api/partyRoleManagement/v4
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/Job-0.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-roleinitialization'
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        impl: 'release-name-roleinitialization'
    spec:
      containers:
      - env:
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'tmfc003-productorderdeliveryorchestrationandmanagement'
        - name: PARTY_ROLE_SVC_NAME
          value: 'release-name-partyrole-management-api'
        image: tmforumorg/partyroleinitializer:latest
        imagePullPolicy: Always
        name: roleinitialization
      restartPolicy: OnFailure
---
# Source: tmfc003-productorderdeliveryorchestrationandmanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
  name: 'release-name-tmfc003-productorderdeliveryorchestrationandmanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: product-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      name: product-ordering-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF622_Product_Ordering/4.0.0/swagger/TMF622_Product_Ordering_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: product-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: service-ordering-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF641_Service_Ordering/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      name: service-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: resource-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF634_Resource_Catalog/4.1.0/swagger/TMF634_Resource_Catalog_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      name: service-ordering-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF641_Service_Ordering/4.1.0/swagger/TMF641_Service_Ordering_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      name: service-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF638_Service_Inventory/4.0.0/swagger/TMF638_Service_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: resource-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: resource-order-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF652_Resource_Order/4.0.0/swagger/TMF652_Resource_Order_Management_API_v4.0.0_swagger.json
  description: 'This component is in charge of the orchestration of the delivery of
    Product Orders (status accepted). Based on the Product specification level of
    information available in the Product Catalog (ex: prerequisite links between product
    specifications, links between product and CFS specifications, ...): it determines
    in which order the product specification level order items need to be delivered,
    and to which CFS (or Resource) specification each ordered product corresponds,
    and prepares and addresses each related service (or resource) order to the production
    system in charge. During the delivery process execution, this component is in
    charge of the evolution of the status of the product specification level order
    items, and of the related product items . So, it triggers the updates of the related
    inventories.'
  functionalBlock: CoreCommerce
  id: TMFC003
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  name: ProductOrderDeliveryOrchestrationAndManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-partyrole-management-api'
      name: partyrole-management-api
      path: /release-name-tmfc003-productorderdeliveryorchestrationandmanagement/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.1
