component:
  id: tmfc005
  name: tmfc005-productinventory
  publicationDate: '2023-08-18T00:00:00.000Z'
images:
  tmf637: tmforumorg/tmfc005-tmf637-v4.0.0:latest
  tmf669: tmforumorg/tmfc005-tmf669-v4.0.0:latest
security:
  controllerRole: admin
