---
# Source: tmfc006-servicecatalogmanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc006-servicecatalogmanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-service-catalog-management-api'
spec:
  ports:
  - name: tcp-release-name-service
    port: 8080
    targetPort: 'release-name-service'
  selector:
    impl: 'release-name-service-catalog-management-api'
---
# Source: tmfc006-servicecatalogmanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-service-catalog-management-api'
spec:
  ports:
  - name: tcp-release-name-service
    port: 8080
    targetPort: 'release-name-service'
  selector:
    impl: 'release-name-service-catalog-management-api'
---
# Source: tmfc006-servicecatalogmanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-party-role-management-api'
spec:
  ports:
  - name: tcp-release-name-party-r
    port: 8080
    targetPort: 'release-name-party-r'
  selector:
    impl: 'release-name-party-role-management-api'
---
# Source: tmfc006-servicecatalogmanagement/templates/Service-3.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc006-servicecatalogmanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-service-catalog-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-service-catalog-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc006-servicecatalogmanagement'
        impl: 'release-name-service-catalog-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc006-servicecatalogmanagement'
        image: 'tmforumorg/tmfc006-tmf633-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-service-catalog-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-service'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc006-servicecatalogmanagement/tmf-api/serviceCatalogManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc006-servicecatalogmanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-service-catalog-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-service-catalog-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc006-servicecatalogmanagement'
        impl: 'release-name-service-catalog-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc006-servicecatalogmanagement'
        image: 'tmforumorg/tmfc006-tmf633-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-service-catalog-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-service'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc006-servicecatalogmanagement/tmf-api/serviceCatalogManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc006-servicecatalogmanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-party-role-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-party-role-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc006-servicecatalogmanagement'
        impl: 'release-name-party-role-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc006-servicecatalogmanagement'
        image: 'tmforumorg/tmfc006-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-party-role-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-party-r'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc006-servicecatalogmanagement/tmf-api/partyRoleManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc006-servicecatalogmanagement/templates/Deployment-3.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc006-servicecatalogmanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc006-servicecatalogmanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc006-servicecatalogmanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc006-servicecatalogmanagement'
  name: 'release-name-tmfc006-servicecatalogmanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: entity-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF662_Entity_Catalog/4.0.0/swagger/TMF662_Entity_Catalog_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: user-role-permission-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-service-catalog-management-api'
      name: service-catalog-management-api
      path: /release-name-tmfc006-servicecatalogmanagement/tmf-api/serviceCatalogManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      implementation: 'release-name-service-catalog-management-api'
      name: service-catalog-management-api
      path: /release-name-tmfc006-servicecatalogmanagement/tmf-api/serviceCatalogManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF633_Service_Catalog/4.0.0/swagger/TMF633_Service_Catalog_Management_API_v4.0.0_swagger.json
  description: "\tService Catalog Management component is responsible for organizing\
    \ the collection of service specifications that identify and define all requirements\
    \ of a service that can be performed. Service Catalog Management component has\
    \ the functionality that enable present a customer-facing view so users are able\
    \ to search and select services they need, as well as a technical view to enable\
    \ define and setup what's needed to deliver service specifications (Customer Facing\
    \ Service Specifications (CFSSs) and Resource Facing Service Specifications (RFSSs))\
    \ contained in the service catalog. Service Catalog Management component has functionalities\
    \ that include creation of new service specifications, managing service specifications,\
    \ administering the lifecycle of services, describing relationships between service\
    \ specification attributes, reporting on service specification and their changes,\
    \ and facilitating easy and systematic indexing and access to services, as well\
    \ as facilitate automating the service delivery process."
  functionalBlock: Production
  id: TMFC006
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: 'release-name-tmfc006-servicecatalogmanagement-sm'
      name: metrics
      path: /release-name-tmfc006-servicecatalogmanagement/metrics
      port: 4000
  name: ServiceCatalogManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-party-role-management-api'
      name: party-role-management-api
      path: /release-name-tmfc006-servicecatalogmanagement/tmf-api/partyRoleManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.1
