apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      id: TMF672
      name: UserRolesandPermissions
      required: true
      resources:
      - permission:
        - GET
        - GET/id
      - role:
        - GET
        - GET/id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF669
      name: PartyRoleManagement
      required: true
      resources:
      - partyRole:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF673
      name: GeographicAddressManagement
      required: false
      resources:
      - GeographicAddress:
        - GET
        - GET /id
      - apitype: openapi
        id: TMF674
        isRequired: 'no'
        name: GeographicSiteManagement
        resources: null
        specification: https://github.com/tmforum-apis/TMF674-GeographicSiteManagement/blob/master/TMF674-GeographicSiteManagement-v4.0.0.swagger.json
        version: 4
      - GeographicSite:
        - GET
        - GET /id
      - apitype: openapi
        id: TMF675
        isRequired: 'no'
        name: GeographicLocationManagement
        resources: null
        specification: https://github.com/tmforum-apis/TMF675-GeographicLocationManagement/blob/master/TMF675-GeographicLocationManagement-v4.0.0.swagger.json
        version: 4
      - GeographicLocation:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF673-GeographicAddressManagement/blob/master/TMF673-GeographicAddressManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF701
      name: ProcessFlowManagement
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF688
      name: Event
      required: false
      resources:
      - event:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      version: 4
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartnershipTypeManagement/v4/docs
      id: TMF668
      implementation: /{{.Release.Name}}-partnermngtapi
      name: PartnershipTypeManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartnershipTypeManagement/v4
      port: 8080
      required: false
      resources:
      - partnershipSpecification:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF668-PartnershipTypeManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
      id: TMF632
      implementation: /{{.Release.Name}}-partymngtapi
      name: PartyManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4
      port: 8080
      required: true
      resources:
      - individual:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      - organization:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF632-PartyManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/CustomerManagement/v4/docs
      id: TMF629
      implementation: /{{.Release.Name}}-custmngtapi
      name: CustomerManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/CustomerManagement/v4
      port: 8080
      required: false
      resources:
      - customer:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE/id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF629-CustomerManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      id: TMF701
      implementation: /{{.Release.Name}}-procmngttapi
      name: ProcessFlowManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      port: 8080
      required: false
      resources:
      - processFloe:
        - GET
        - GET/id
        - POST
        - DELETE/id
      - taskFlow:
        - GET
        - GET/id
        - PATCH/id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-PromotionManagement
      name: EventManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      port: 8080
      required: false
      resources:
      - event:
        - GET
        - GET /id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF671-Promotion-v4.0.0.swagger.json
      version: 4
    publishedEvents:
    - apitype: openapi
      implementation: /{{.Release.Name}}-partnermngtapi
      name: PartnershipTypeMaagement
      port: 80
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF668_PartnershipTypeManagement/master/TMF668-PartnershipTypeManagement-v4.0.0.swagger.json
    - resources:
        Partnership:
        - PartnershipCreateEvent
        - PartnershipChangeEvent
        - PartnershipDeleteEvent
        PartnershipSpecification:
        - PartnershipSpecificationCreateEvent
        - PartnershipSpecificationChangeEvent
        - PartnershipSpecificationDeleteEvent
    - apitype: openapi
      implementation: /{{.Release.Name}}-partymngtapi
      name: partyManagement
      port: 80
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    - resources:
        Individual:
        - IndividualCreateEvent
        - IndividualAttributeValueChangeEvent
        - IndividualStateChangeEvent
        - IndividualDeleteEvent
        Organization:
        - OrganizationCreateEvent
        - OrganizationAttributeValueChangeEvent
        - OrganizationStateChangeEvent
        - OrganizationDeleteEvent
    - apitype: openapi
      implementation: /{{.Release.Name}}-custmngtapi
      name: CustomerManagement
      port: 80
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF629_CustomerManagement/master/TMF629-CustomerManagement-v4.0.0.swagger.json
    - resources:
        customer:
        - CustomerCreateEvent
        - CustomerAttributeValueChangeEvent
        - CustomerStateChangeEvent
        - CustomerDeleteEvent
    subscribedEvents:
    - apitype: openapi
      name: UserRolesandPermissions
      port: 80
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
    - resources:
        UserRoles:
        - UserRoleCreationNotification
        - UserRoleChangeNotification
    - apitype: openapi
      name: PartyRoleManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    - resources:
        PartyRole:
        - PartyRoleCreateEvent
        - PartyRoleAttributeValueChangeEvent
        - PartyRoleStateChangeEvent
        - PartyRoleDeleteEvent
  description: 'Party Management component is responsible for the capture, validation
    and management of Parties and their Roles. A Party may be an individual or organization
    that has a relationship with an enterprise. In this context it is responsible
    for the e2e life cycle of: Individual, Organization. and its related sub-entities:Contact
    Medium, Currency and tax exemption certificates, Identification, Community'
  functionalBlock: PartyManagement
  id: TMFC028
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: PartyManagement
  owners:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  publicationDate: 2023-08-18 00:00:00+00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 1.3.1
