apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceCatalog
      name: ResourceCatalogManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
      port: 8080
      required: true
      resources:
      - resourceCatalog:
        - GET
        - GET /id
      - resourceCategory:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceSpecification:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - resourceCandidate:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - exportJob:
        - GET
        - POST
        - DELETE
      - importJob:
        - GET
        - POST
        - DELETE
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
      version: 4.1
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/v4/docs
      id: TMF669
      implementation: /{{.Release.Name}}-PartyRole
      name: PartyRoleManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/v4.0
      port: 8080
      required: false
      resources:
      - partyRole: -GET -GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4/docs
      id: TMF632
      implementation: /{{.Release.Name}}-Party
      name: Party
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/v4
      port: 8080
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_Party/master/TMF632-Party-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4/docs
      id: TMF673
      implementation: /{{.Release.Name}}-GeographicAddressManagement
      name: GeographicAddressManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
      port: 8080
      required: true
      resources:
      - geographicAddress:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF673_GeographicAddress/master/TMF673-GeographicAddress-v4.0.1.swagger.json
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
      id: TMF674
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      name: GeographicSiteManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
      port: 8080
      required: true
      resources:
      - geographicSite:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF674_GeographicSite/master/TMF674-GeographicSite-v4.0.0.swagger.json
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4/docs
      id: TMF675
      implementation: /{{.Release.Name}}-GeographicLocation
      name: GeographicLocation
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/v4
      port: 8080
      required: true
      resources:
      - geographicLocation:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF675_GeographicLocation/master/TMF675-GeographicLocation-v4.0.0.swagger.json
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4/docs
      id: TMF672
      implementation: /{{.Release.Name}}-UserRolesPermissions
      name: UserRolesPermissions
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolesPermissions/v4
      port: 8080
      required: true
      resources:
      - permission:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesPermissions/master/TMF672-UserRolePermission-v4.0.0.swagger.json
      version: 4
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF639
      implementation: /{{.Release.Name}}-ResourceInventory
      name: ResourceInventoryManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4
      port: 8080
      required: true
      resources:
      - resource:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-Event
      name: Event
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
      port: 8080
      required: false
      resources:
      - event:
        - POST
        - DELETE
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF688-Event/master/TMF688-Event-v4.0.0.swagger.json
      version: 4
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF639
      implementation: /{{.Release.Name}}-ResourceInventory
      name: ResourceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4.1.0
      port: 8080
      required: true
      resources:
      - resource:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF639-ResourceInventory-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PoolManagement/v4/docs
      id: TMF685
      implementation: /{{.Release.Name}}-PoolManagement
      name: ResourcePoolManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PoolManagement/v4
      port: 8080
      required: false
      resources:
      - resourcePool:
        - POST
        - PATCH
        - DELETE
      - reservation:
        - GET
        - GET /id
        - POST
        - PATCH
      - availabilityCheck:
        - GET
        - GET /id
        - POST
      - push:
        - GET
        - GET /id
        - POST
      - extract:
        - GET
        - GET /id
        - POST
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/Resource_Pool_.admin.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      name: ProcessFlowManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      port: 8080
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF701-ProcessFlow-v4.1.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-Event
      name: Event
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Event/v4
      port: 8080
      required: false
      resources:
      - event:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF688-Event-v4.0.0.swagger.json
      version: 4
    publishedEvents:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceInventory
      isRequired: 'yes'
      name: ResourceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4.1.0
      port: 8080
      resources:
        resource:
        - resourceCreateEvent
        - resourceChangeEvent
        - resourceDeleteEvent
        - resourceAttributeValueChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourcePool/v4/docs
      id: TMF685
      implementation: /{{.Release.Name}}-ResourcePool
      isRequired: 'yes'
      name: ResourcePoolManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourcePool/v4.1.0
      port: 8080
      resources:
        resourcePool:
        - reservationStateChangeNotification
        - informationRequiredNotification
        - resourceReservationCreationEvent
        - resourceReservationRemoveEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF685_ResourcePool/master/Resource_Pool_Management.admin.swagger.json
      version: 4
    - -resources:
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
      apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4/docs
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceCatalog
      isRequired: 'yes'
      name: ResourceCatalogManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceCatalog/v4.1.0
      port: 8080
      resources:
        ResourceCatalogManagement:
        - resourceCatalogCreateEvent
        - resourceCatalogChangeEvent
        - resourceCatalogDeleteEvent
        - resourceCategoryCreateEvent
        - resourceCategoryChangeEvent
        - resourceCategoryDeleteEvent
        - resourceCandidateCreateEvent
        - resourceCandidateChangeEvent
        - resourceCandidateDeleteEvent
        - resourceSpecificationCreateEvent
        - resourceSpecificationChangeEvent
        - resourceSpecificationDeleteEvent
        - importJobCreateEvent
        - exportJobCreateEvent
        - exportJobStateChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF634_resourceCatalog/master/TMF634_resourceCatalog-v4.1.0.swagger.json
      version: 4.1
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF634
      implementation: /{{.Release.Name}}-ResourceInventory
      isRequired: 'yes'
      name: ResourceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4.1.0
      port: 8080
      resources:
        resource:
        - resourceCreateEvent
        - resourceChangeEvent
        - resourceDeleteEvent
        - resourceAttributeValueChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      name: PartyRoleManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    - resources:
        PartyRole:
        - PartyRoleCreateEvent
        - PartyRoleAttributeValueChangeEvent
        - PartyRoleStateChangeEvent
        - PartyRoleDeleteEvent
    - apitype: openapi
      name: UserRolesandPermissions
      port: 80
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF672_UserRolesandPermissions/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
    - resources:
        UserRoles:
        - UserRoleCreationNotification
        - UserRoleChangeNotification
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSite/call-back
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      name: GeographicSiteManagement
      port: 80
      resources:
      - GeographicSite:
        - geographicSiteDeleteEvent
      specification: https://open-api.tmforum.org20-GeographicSite-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/call-back
      implementation: /{{.Release.Name}}-GeographicLocation
      name: GeographicLocation
      port: 80
      resources:
      - GeographicLocation:
        - geographicLocationDeleteEvent
      specification: https://open-api.tmforum.org20-GeographicLocatin-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/call-back
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - Party:
        - individualDeleteEvent
        - organizationDeleteEvent
      specification: https://open-api.tmforum.org20-Party-v4.0.0.swagger.json
  description: Resource Inventory component is responsible for accounting for resources
    (all inputs - including stock, parts, assets, production components etc.) that
    are owned and/or held for allocation and/or use by the organization. Resource
    Inventory component has functionality that includes inventory items creation,
    inventory organization, inventory search or filter, inventory monitoring and tracking,
    inventory control (organization, re-stock management etc.) and inventory auditing.
    The minimum check to be performed at inventory items creation or update is the
    global consistency with related Resource Catalog information.
  functionalBlock: Production
  id: TMFC012
  maintainers:
  - email: sylvie.demarest@orange.com
    name: Sylvie Demarest
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: ResourceInventory
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: 2023-08-18 00:00:00+00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 2.0.0
