---
# Source: tmfc020-digitalidentitymanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc020-digitalidentitymanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-digital-identity-management-api'
spec:
  ports:
  - name: tcp-release-name-digital
    port: 8080
    targetPort: 'release-name-digital'
  selector:
    impl: 'release-name-digital-identity-management-api'
---
# Source: tmfc020-digitalidentitymanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-partyrole-management-api'
spec:
  ports:
  - name: tcp-release-name-partyro
    port: 8080
    targetPort: 'release-name-partyro'
  selector:
    impl: 'release-name-partyrole-management-api'
---
# Source: tmfc020-digitalidentitymanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc020-digitalidentitymanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-digital-identity-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-digital-identity-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc020-digitalidentitymanagement'
        impl: 'release-name-digital-identity-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc020-digitalidentitymanagement'
        image: 'tmforumorg/tmfc020-tmf720-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-digital-identity-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-digital'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc020-digitalidentitymanagement/tmf-api/digitalIdentityManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc020-digitalidentitymanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-partyrole-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-partyrole-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc020-digitalidentitymanagement'
        impl: 'release-name-partyrole-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc020-digitalidentitymanagement'
        image: 'tmforumorg/tmfc020-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-partyrole-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-partyro'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc020-digitalidentitymanagement/tmf-api/partyRoleManagement/v4
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc020-digitalidentitymanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc020-digitalidentitymanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc020-digitalidentitymanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc020-digitalidentitymanagement/templates/Job-0.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-roleinitialization'
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        impl: 'release-name-roleinitialization'
    spec:
      containers:
      - env:
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'tmfc020-digitalidentitymanagement'
        - name: PARTY_ROLE_SVC_NAME
          value: 'release-name-partyrole-management-api'
        image: tmforumorg/partyroleinitializer:latest
        imagePullPolicy: Always
        name: roleinitialization
      restartPolicy: OnFailure
---
# Source: tmfc020-digitalidentitymanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc020-digitalidentitymanagement'
  name: 'release-name-tmfc020-digitalidentitymanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-digital-identity-management-api'
      name: digital-identity-management-api
      path: /release-name-tmfc020-digitalidentitymanagement/tmf-api/digitalIdentityManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF720_Digital_Identity/4.0.0/swagger/TMF720_Digital_Identity_Management_API_v4.0.0_swagger.json
  description: The Digital Identity Management is responsible for the parties (customers,
    employees, partners) and resources authentication.
  functionalBlock: PartyManagement
  id: TMFC020
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  name: DigitalIdentityManagement
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-partyrole-management-api'
      name: partyrole-management-api
      path: /release-name-tmfc020-digitalidentitymanagement/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.1
