apiVersion: oda.tmforum.org/v1beta2
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF620
    isRequired: true
    name: ProductCatalogManagement
    resources:
    - productSpecification:
      - GET
      - GET /id
    - productOffering:
      - GET
      - GET /id
    - productOfferingPrice:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF620_ProducCatalogManagement/master/TMF637-ProducCatalogManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF669
    isRequired: false
    name: PartyRoleManagement
    resources:
    - PartyRoleManagement:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF639
    isRequired: false
    name: ResourceInventory
    resource:
    - resource:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF639-ResourceInventory/master/TMF639-ResourceInventory-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF651
    isRequired: false
    name: AgreementManagement
    resources:
    - agreement:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF673
    isRequired: false
    name: GeographicAddressManagement
    resources:
    - geographicAddress:
      - GET
      - GET /id
    - geographicSubAddress:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF674
    isRequired: false
    name: GeographicSiteManagement
    resources:
    - geographicSite:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF674_GeographicSite/blob/master/TMF674-GeographicSite-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF675
    isRequired: false
    name: GeographicLocation
    resources:
    - geographicLocation:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF675_GeographicLocation/blob/master/TMF675-GeographicLocation-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF672
    isRequired: false
    name: UserRolePermission
    resources:
    - permission:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF672_UserRolesPermissions/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF666
    isRequired: false
    name: AccountManagement
    resources:
    - billingAccount:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF666_AccountManagement/blob/master/TMF666_AccountManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF632
    isRequired: false
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET /id
    - organization:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF632_Party/blob/master/TMF632-Party-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF637
    isRequired: false
    name: ProductInventory
    resources:
    - product:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://github.com/tmforum-apis/TMF637_ProducInventory/blob/master/TMF637-ProducInventory-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF638
    isRequired: false
    name: ServiceInventory
    resources:
    - service:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF638_ServiceInventory/blob/master/TMF638_ServiceInventory-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF622
    isRequired: false
    name: ProductOrdering
    resources:
    - productOrder:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF622_ProductOrdering/blob/master/TMF622_ProductOrdering-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF688
    isRequired: false
    name: Event
    resources:
    - event:
      - GET
      - GET /id
      - POST
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productinventory/v4/docs
    id: TMF637
    implementation: /{{.Release.Name}}-prodinvapi
    isRequired: true
    name: productinventory
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productinventory/v4
    port: 8080
    resources:
    - product:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF637-ProductInventory-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    isRequired: false
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: ttps://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-EventManagement
    isRequired: false
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
    port: 8080
    resources:
    - listener:
      - POST
    - hub:
      - POST
      - DELETE
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF688_Event/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  publishedEvents:
  - -resources:
      Productinventory:
      - productCreateEvent
      - productAttributeValueChangeEvent
      - productStateChangeEvent
      - productDeleteEvent
      - productBatchEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/productinventory/hub
    implementation: /{{.Release.Name}}-ProductinventoryEvent
    name: Productinventory
    port: 80
    specification: https://github.com/tmforum-apis/TMF637_ProducInventory/blob/master/TMF637-ProducInventory-v4.0.0.swagger.json
  - -resources:
      ProcessFlow:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
    implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
    name: ProcessFlowManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Resource/call-back
    implementation: /{{.Release.Name}}-ResourceInventoryManagement
    name: ResourceInventoryManagement
    port: 80
    resources:
    - ResourceInventory:
      - resourceDeleteEvent
    specification: https://open-api.tmforum.org20-ResourceInventory-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/call-back
    implementation: /{{.Release.Name}}-ServiceInventoryManagement
    name: ServiceInventoryManagement
    port: 80
    resources:
    - ServiceInventory:
      - serviceDeleteEvent
    specification: https://open-api.tmforum.org20-ServiceInventory-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalog/call-back
    implementation: /{{.Release.Name}}-ProductCatalogManagement
    name: ProductCatalogManagement
    port: 80
    resources:
    - ProductCatalog:
      - productSpecificationDeleteEvent
      - productOfferingDeleteEvent
      - productOfferingPriceDeleteEvent
    specification: https://open-api.tmforum.org20-ProductCatalog-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRole/call-back
    implementation: /{{.Release.Name}}-PartyRoleManagement
    name: PartyRoleManagement
    port: 80
    resources:
    - PartyRole:
      - partyRoleDeleteEvent
    specification: https://open-api.tmforum.org20-PartyRole-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Agreement/call-back
    implementation: /{{.Release.Name}}-AgreementManagement
    name: AgreementManagement
    port: 80
    resources:
    - Agreement:
      - agreementDeleteEvent
    specification: https://open-api.tmforum.org20-Agreement-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Account/call-back
    implementation: /{{.Release.Name}}-AccountManagement
    name: AccountManagement
    port: 80
    resources:
    - Account:
      - billingAccountDeleteEvent
    specification: https://open-api.tmforum.org20-Account-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/UserRolePermission/call-back
    implementation: /{{.Release.Name}}-UserRolePermissionManagement
    name: UserRolePermissionManagement
    port: 80
    resources:
    - UserRolePermission:
      - permissionDeleteEvent
    specification: https://open-api.tmforum.org20-UserRolePermission-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSite/call-back
    implementation: /{{.Release.Name}}-GeographicSiteManagement
    name: GeographicSiteManagement
    port: 80
    resources:
    - GeographicSite:
      - geographicSiteDeleteEvent
    specification: https://open-api.tmforum.org20-GeographicSite-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicLocation/call-back
    implementation: /{{.Release.Name}}-GeographicLocation
    name: GeographicLocation
    port: 80
    resources:
    - GeographicLocation:
      - geographicLocationDeleteEvent
    specification: https://open-api.tmforum.org20-GeographicLocatin-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Party/call-back
    implementation: /{{.Release.Name}}-PartyManagement
    name: PartyManagement
    port: 80
    resources:
    - Party:
      - individualDeleteEvent
      - organizationDeleteEvent
    specification: https://open-api.tmforum.org20-Party-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOrdering/call-back
    implementation: /{{.Release.Name}}-ProductOrderingManagement
    name: ProductOrderingManagement
    port: 80
    resources:
    - ProductOrdering:
      - productOrderDeleteEvent
    specification: https://open-api.tmforum.org20-ProductOrdering-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductInventory/call-back
    implementation: /{{.Release.Name}}-ProductInventoryManagement
    name: ProductInventoryManagement
    port: 80
    resources:
    - ProductInventory:
      - productCreateEvent
      - productDeleteEvent
      - productAttributeValueChangeEvent
      - productStateChangeEvent
    specification: https://open-api.tmforum.org20-ProductInventory-v4.0.0.swagger.json
kind: component
managementFunction: []
metadata:
  name: components.oda.tmforum.org
reportingFunction: []
securityFunction: []
spec:
  componenentDescription: Product  Inventory component is responsible for storage
    and exposure of products that are assigned to and used by Parties. Product Inventory
    component has functionality that enables inventory items creation, inventory organization,
    inventory search or filter, inventory monitoring and tracking, inventory control
    and inventory auditing. The minimum check to be performed at inventory items creation
    or update is the global consistency with related Product Catalog information.
  componentFunctionalBlock: CoreCommerceManagement
  componentId: TMFC005
  componentName: ProductInventory
  componentPublicationDate: 2023-08-18
  componentStatus: specified
  componentVersion: 1.1.1
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
