apiVersion: oda.tmforum.org/v1beta2
kind: component
managementFunction: []
metadata:
  name: components.oda.tmforum.org
reportingFunction: []
securityFunction: []
spec:
  componenentDescription: Service Performance Management will monitor, analyze, and
    report on the end-end service performance. This can include a real-time, end-to-end
    view to ensure that each service is functioning correctly as well as a historical
    view. These functions build on the Resource Performance data and active end-end
    service performance test data to provide a view of a service. The component provides
    a key input to determine the Quality of Service.
  componentFunctionalBlock: IntelligenceManagement
  componentId: TMFC037
  componentName: ServicePerformanceManagement
  componentPublicationDate: 2023-08-18
  componentStatus: specified
  componentVersion: 1.1.0
  coreFunction:
    PublishedEvent:
    - -resources:
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
      apitype: null
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-processFlowEvent
      name: ProcessFlowManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF701-ProcessFlowManagement/blob/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    - -resources:
        AlarmManagement:
        - alarmStateChange**
        - alarmCreateEvent**
        - alarmClearEvent**
        - alarmAckEvent**
      apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AlarmManagement/hub
      implementation: /{{.Release.Name}}-AlarmManagement
      name: AlarmManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF642_AlarmManagement/blob/master/TMF642-Alarm-v4.0.0.swagger.json
    - -resources:
        PerformanceManagement:
        - measurementCollectionJobCreateEvent
        - measurementCollectionJobExecutionStateChangeEvent
        - measurementCollectionJobDeleteEvent
        - measurementCollectionJobAttributeValueChangeEvent
        - measurementCollectionJobFilesReadyEvent
        - measurementCollectionJobFilesPreparationErrorEvent
        - onDemandCollectionCreateEvent
        - onDemandCollectionExecutionStateChangeEvent
        - onDemandCollectionDeleteEvent
        - onDemandCollectionAttributeValueChangeEvent
        - onDemandCollectionFilesReadyEvent
        - onDemandCollectionFilesPreparationErrorEvent
        PerformanceThresholdManagement:
        - thresholdCreateNotification
        - thresholdChangeNotification
        - thresholdRuleCreateNotification
        - thresholdRuleChangedNotification
        - thresholdJobCreateNotification
        - thresholdJobChangedNotification
        - thresholdJobSuspendNotification
        - thresholdJobResumeNotification
      apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/hub
      implementation: /{{.Release.Name}}-PerformanceManagement
      name: PerformanceManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF628-Performance-v4.1.0.swagger.json
    SubscribedEvent:
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceCatalog/call-back
      implementation: /{{.Release.Name}}-ServiceCatalogManagement
      name: ServiceCatalogManagement
      port: 80
      resources:
      - ServiceCatalog:
        - serviceSpecificationChangeEvent
      specification: https://github.com/tmforum-apis/TMF633_ServiceCatalog/blob/master/TMF633-ServiceCatalog-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceInventory/call-back
      implementation: /{{.Release.Name}}-ServiceInventoryManagement
      name: ServiceInventoryManagement
      port: 80
      resources:
      - ServiceInventory:
        - serviceCreateEvent
        - serviceAttributeValueChangeEvent
        - serviceStateChangeEvent
        - serviceDeleteEvent
      specification: https://github.com/tmforum-apis/TMF638_ServiceInventory/blob/master/TMF638-ServiceInventory-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/call-back
      implementation: /{{.Release.Name}}-ResourceInventory
      name: ResourceInventoryManagement
      port: 80
      resources:
      - ResourceInventory:
        - resourceCreateEvent
        - resourceAttributeValueChangeEvent
        - resourceStateChangeEvent
        - resourceDeleteEvent
      specification: https://github.com/tmforum-apis/TMF639_ResourceInventory/blob/master/TMF639-ResourceInventory-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/call-back
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      name: ProcessFlowManagement
      port: 80
      resources:
      - ProcessFlow:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
      specification: https://github.com/tmforum-apis/TMF701-ProcessFlowManagement/blob/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    dependantAPIs:
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4/docs
      id: TMF628
      implementation: /{{.Release.Name}}-PerformanceManagement
      isRequired: false
      name: PerformanceManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4
      port: 8080
      resources:
      - measurementCollectionJob*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - onDemandCollection*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - performanceIndicatorGroupSpecification*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - performanceIndicatorSpecification*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - trackingRecord*:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF628-Performance-v4.0.0.swagger.json
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF639
      implementation: /{{.Release.Name}}-ResourceInventory
      isRequired: false
      name: ResourceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4
      port: 8080
      resources:
      - resource:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF639_ResourceInventory/blob/master/TMF639-ResourceInventory-v4.0.0.swagger.json
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4/docs
      id: TMF638
      implementation: /{{.Release.Name}}-ResourceInventory
      isRequired: false
      name: ServiceInventory
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ResourceInventory/v4
      port: 8080
      resources:
      - service:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF639_ResourceInventory/blob/master/TMF639-ResourceInventory-v4.0.0.swagger.json
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagementt/v4/docs
      id: TMF673
      implementation: /{{.Release.Name}}-GeographicAddressManagement
      isRequired: false
      name: GeographicAddressManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicAddressManagement/v4
      port: 8080
      resources:
      - geographicAddress:
        - GET
        - GET/id
      - geographicSubAddress:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF673_GeographicAddress/blob/master/TMF673-GeographicAddress-v4.0.1.swagger.json
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4/docs
      id: TMF674
      implementation: /{{.Release.Name}}-GeographicSiteManagement
      isRequired: false
      name: GeographicSiteManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/GeographicSiteManagement/v4
      port: 8080
      resources:
      - geographicSite:
        - GET
        - GET/id
      specification: https://github.com/tmforum-apis/TMF674_GeographicSite/blob/master/TMF674-GeographicSite-v4.0.0.swagger.json
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualityManagement/v4/docs
      id: TMF657
      implementation: /{{.Release.Name}}-ServiceQualityManagement
      isRequired: false
      name: ServiceQualityManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ServiceQualityManagement/v4
      port: 8080
      resources:
      - serviceLevelObjective:
        - GET
        - GET/id
      - serviceLevelSpecification:
        - GET
        - GET/id
      specification: https://github.com/tmforum-apis/TMF657_ServiceQualityManagement/blob/master/TMF675-ServiceQualityManagement-v4.0.0.swagger.json
    - apitype: openapi
      id: TMF688
      isRequired: false
      name: Event
      resources:
      - event:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      version: 4.0
    - apitype: openapi
      id: TMF701
      isRequired: false
      name: ProcessFlowManagement
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
      version: 4.0
    exposedAPIs:
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4/docs
      id: TMF628
      implementation: /{{.Release.Name}}-PerformanceManagement
      isRequired: true
      name: PerformanceManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceManagement/v4
      port: 8080
      resources:
      - measurementCollectionJob*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - onDemandCollection*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - performanceIndicatorGroupSpecification*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - performanceIndicatorSpecification*:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - trackingRecord*:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF628_Performance/blob/main/TMF628-Performance-v4.0.0.swagger.json
      version: 4.0
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceThresholdManagement/v4/docs
      id: TMF649
      implementation: /{{.Release.Name}}-PerformanceManagement
      isRequired: true
      name: PerformanceThresholdManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PerformanceThresholdManagement/v4
      port: 8080
      resources:
      - threshold:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      - thresholdJob:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      specification: https://github.com/tmforum-apis/TMF649_Performance/blob/main/TMF628-Performance-v4.0.0.swagger.json
      version: 4.0
    - developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AlarmManagement/v4/docs
      id: TMF642
      implementation: /{{.Release.Name}}-AlarmManagement
      isRequired: false
      name: AlarmManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AlarmManagement/v4
      port: 8080
      resources:
      - alarm:
        - POST
        - GET
        - GET /id
        - PATCH /id
        - DELETE /id
      specification: https://github.com/tmforum-apis/TMF642_AlarmManagement/blob/master/TMF642-Alarm-v4.0.0.swagger.json
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      id: TMF701
      implementation: /{{.Release.Name}}-procflowapi
      isRequired: false
      name: ProcessFlowManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      port: 8080
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-PromotionManagement
      isRequired: false
      name: Event
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      port: 8080
      resources:
      - listener:
        - POST
      - hub:
        - POST
        - DELETE
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
      version: 4
  maintainers:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  owners:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
