---
# Source: tmfc038-resourceperformancemanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc038-resourceperformancemanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-alarm-management-api'
spec:
  ports:
  - name: tcp-release-name-alarm-m
    port: 8080
    targetPort: 'release-name-alarm-m'
  selector:
    impl: 'release-name-alarm-management-api'
---
# Source: tmfc038-resourceperformancemanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-partyrole-management-api'
spec:
  ports:
  - name: tcp-release-name-partyro
    port: 8080
    targetPort: 'release-name-partyro'
  selector:
    impl: 'release-name-partyrole-management-api'
---
# Source: tmfc038-resourceperformancemanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc038-resourceperformancemanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-alarm-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-alarm-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc038-resourceperformancemanagement'
        impl: 'release-name-alarm-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc038-resourceperformancemanagement'
        image: 'tmforumorg/tmfc038-tmf642-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-alarm-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-alarm-m'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc038-resourceperformancemanagement/tmf-api/alarm/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc038-resourceperformancemanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-partyrole-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-partyrole-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc038-resourceperformancemanagement'
        impl: 'release-name-partyrole-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc038-resourceperformancemanagement'
        image: 'tmforumorg/tmfc038-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-partyrole-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-partyro'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc038-resourceperformancemanagement/tmf-api/partyRoleManagement/v4
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc038-resourceperformancemanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc038-resourceperformancemanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc038-resourceperformancemanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc038-resourceperformancemanagement/templates/Job-0.yaml
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-roleinitialization'
spec:
  backoffLimit: 10
  template:
    metadata:
      labels:
        impl: 'release-name-roleinitialization'
    spec:
      containers:
      - env:
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'tmfc038-resourceperformancemanagement'
        - name: PARTY_ROLE_SVC_NAME
          value: 'release-name-partyrole-management-api'
        image: tmforumorg/partyroleinitializer:latest
        imagePullPolicy: Always
        name: roleinitialization
      restartPolicy: OnFailure
---
# Source: tmfc038-resourceperformancemanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc038-resourceperformancemanagement'
  name: 'release-name-tmfc038-resourceperformancemanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: resource-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF639_Resource_Inventory/4.0.0/swagger/TMF639_Resource_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: geographic-address-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF673_Geographic_Address/4.0.0/swagger/TMF673_Geographic_Address_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: geographic-site-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF674_Geographic_Site/4.0.0/swagger/TMF674_Geographic_Site_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-alarm-management-api'
      name: alarm-management-api
      path: /release-name-tmfc038-resourceperformancemanagement/tmf-api/alarm/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF642_Alarm/4.0.0/swagger/TMF642_Alarm_Management_API_v4.0.0_swagger.json
  description: Resource Performance Management will monitor, analyze, and report on
    the performance of the service provider's resources.
  functionalBlock: IntelligenceManagement
  id: TMFC038
  maintainers:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  name: ResourcePerformanceManagement
  owners:
  - email: milind.2.bhagwat@bt.com
    name: Milind Bhagwat
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-partyrole-management-api'
      name: partyrole-management-api
      path: /release-name-tmfc038-resourceperformancemanagement/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.0
