apiVersion: oda.tmforum.org/v1beta2
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF632
    isRequired: false
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET /id
    - organization:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF669
    isRequired: false
    name: PartyRoleManagement
    resources:
    - PartyRoleManagement:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF672
    isRequired: false
    name: UserRolePermission
    resources:
    - permission:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF672_UserRolesPermissions/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF662
    isRequired: false
    name: EntityCatalogManagement
    resources:
    - entitySpecification:
      - GET
      - GET /id
    - entityCategory:
      - GET
      - GET /id
    - entityCatalog:
      - GET
      - GET /id
    - entityCatalogItem:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF662_EntityCatalog/blob/master/TMF662-EntityCatalog-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF667
    isRequired: false
    name: DocumentManagement
    resources:
    - document:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF667_Document/blob/master/TMF667-Document-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF688
    isRequired: false
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/v4/docs
    id: TMF683
    implementation: /{{.Release.Name}}-PartyInteractionManagement
    isRequired: true
    name: PartyInteractionManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/v4
    port: 8080
    resources:
    - PartyInteraction:
      - GET
      - GET /id
      - POST
      - PATCH
      - DELETE
    specification: https://github.com/tmforum-apis/TMF683_PartyInteraction/blob/master/partyInteractionManagement_TMF_v1.0.0Review2.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-ProcessFlowManagement
    isRequired: false
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - DELETE
    - taskFlow:
      - PATCH
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: false
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
    port: 8080
    resources:
    - listener:
      - POST
    - hub:
      - POST
      - DELETE
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  publishedEvents:
  - -resources:
      partyInteractionManagement:
      - partyInteractionCreateEvent
      - partyInteractionAttributeValueChangeEvent
      - partyInteractionDeleteEvent
      - partyInteractionStatusChangeEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyInteractionManagement/hub
    implementation: /{{.Release.Name}}-PartyInteractionManagementEvent
    name: PartyInteractionManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF683_PartyInteraction/blob/master/partyInteractionManagement_TMF_v1.0.0Review2.json
  - -resources:
      ProcessFlowManagement:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - processFlowStateDeleteEvent
      - processFlowStateAttributeValueChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
      - taskFlowDeleteEvent
      - taskFlowAttributeValueChangeEvent
      - taskFlowInformationRequiredEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
    implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
    name: ProcessFlowManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
    implementation: /{{.Release.Name}}-PartyManagement
    name: PartyManagement
    port: 80
    resources:
    - Individual:
      - IndividualCreateEvent
      - IndividualAttributeValueChangeEvent
      - IndividualStateChangeEvent
      - IndividualDeleteEvent
    - Organization:
      - OrganizationCreateEvent
      - OrganizationAttributeValueChangeEvent
      - OrganizationStateChangeEvent
      - OrganizationDeleteEvent
    specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
    implementation: /{{.Release.Name}}-PartyRoleManagement
    name: PartyRoleManagement
    port: 80
    resources:
    - PartyRole:
      - PartyRoleCreateEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
  - apitype: openapi
    call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/DocumentgManagement/call-back
    implementation: /{{.Release.Name}}-DocumentgManagementEvent
    name: documentManagement
    port: 80
    resources:
    - documentManagement:
      - documentChangeEvent
      - documentSpecificationAttributeValueChangeEvent
    specification: https://github.com/tmforum-apis/TMF667_Document/blob/master/TMF667-Document-v4.0.0.swagger.json
  - -resources:
      ProcessFlowManagement:
      - processFlowCreateEvent
      - processFlowStateChangeEvent
      - taskFlowCreateEvent
      - taskFlowStateChangeEvent
    apitype: openapi
    hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
    implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
    name: ProcessFlowManagement
    port: 80
    specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.0.0.swagger.json
kind: component
managementFunction:
  exposedAPIs:
  - apitype: prometheus
    implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
    name: metrics
    path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
    port: 4000
metadata:
  name: components.oda.tmforum.org
reportingFunction: []
securityFunction:
  controllerRole: '{{ .Values.security.controllerRole }}'
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
    implementation: '{{.Release.Name}}-partyroleapi'
    name: partyrole
    path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
    port: 8080
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
spec:
  componenentDescription: Party Interaction deals with the initial greeting and welcoming
    of a new contact. This will typically be the first component in a customer experience
    journey, shared by unassisted (self-service, retail kiosk) or assisted (call center,
    retail store) channels. It will identify known parties or new parties and react
    appropriately to propose available actions. It records all the interactions for
    the parties from all channels.
  componentFunctionalBlock: PartyManagement
  componentId: TMFC023
  componentName: PartyInteractionManagement
  componentPublicationDate: 2023-08-18
  componentStatus: specified
  componentVersion: 1.1.1
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
