---
# Source: tmfc040-productusagemanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc040-productusagemanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-usage-management-api'
spec:
  ports:
  - name: tcp-release-name-usage-m
    port: 8080
    targetPort: 'release-name-usage-m'
  selector:
    impl: 'release-name-usage-management-api'
---
# Source: tmfc040-productusagemanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-usage-consumption-management-api'
spec:
  ports:
  - name: tcp-release-name-usage-c
    port: 8080
    targetPort: 'release-name-usage-c'
  selector:
    impl: 'release-name-usage-consumption-management-api'
---
# Source: tmfc040-productusagemanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-party-role-management-api'
spec:
  ports:
  - name: tcp-release-name-party-r
    port: 8080
    targetPort: 'release-name-party-r'
  selector:
    impl: 'release-name-party-role-management-api'
---
# Source: tmfc040-productusagemanagement/templates/Service-3.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc040-productusagemanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-usage-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-usage-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc040-productusagemanagement'
        impl: 'release-name-usage-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc040-productusagemanagement'
        image: 'tmforumorg/tmfc040-tmf635-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-usage-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-usage-m'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc040-productusagemanagement/tmf-api/usageManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc040-productusagemanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-usage-consumption-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-usage-consumption-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc040-productusagemanagement'
        impl: 'release-name-usage-consumption-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc040-productusagemanagement'
        image: 'tmforumorg/tmfc040-tmf677-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-usage-consumption-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-usage-c'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc040-productusagemanagement/tmf-api/usageConsumption/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc040-productusagemanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-party-role-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-party-role-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc040-productusagemanagement'
        impl: 'release-name-party-role-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc040-productusagemanagement'
        image: 'tmforumorg/tmfc040-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-party-role-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-party-r'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc040-productusagemanagement/tmf-api/partyRoleManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc040-productusagemanagement/templates/Deployment-3.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc040-productusagemanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc040-productusagemanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc040-productusagemanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc040-productusagemanagement'
  name: 'release-name-tmfc040-productusagemanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: product-inventory-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF637_Product_Inventory/4.0.0/swagger/TMF637_Product_Inventory_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: user-role-permission-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-usage-management-api'
      name: usage-management-api
      path: /release-name-tmfc040-productusagemanagement/tmf-api/usageManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF635_Usage/4.0.0/swagger/TMF635_Usage_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      implementation: 'release-name-usage-consumption-management-api'
      name: usage-consumption-management-api
      path: /release-name-tmfc040-productusagemanagement/tmf-api/usageConsumption/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF677_Usage_Consumption/4.0.0/swagger/TMF677_Usage_Consumption_Management_API_v4.0.0_swagger.json
  description: Provides standardized mechanism for product usage management such as
    creation, update, retrieval, import and export of a collection of usages. It allows
    a service provider to 1) retrieve usage generated by a partner service platform
    in order to rate it and 2) to provide rated usage to a partner for consumption
    follow-up purposes.
  functionalBlock: CoreCommerce
  id: TMFC040
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: elisabeth.andersson@matrixx.com
    name: Elisabeth Andersson
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: 'release-name-tmfc040-productusagemanagement-sm'
      name: metrics
      path: /release-name-tmfc040-productusagemanagement/metrics
      port: 4000
  name: ProductUsageManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  - email: elisabeth.andersson@matrixx.com
    name: Elisabeth Andersson
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-party-role-management-api'
      name: party-role-management-api
      path: /release-name-tmfc040-productusagemanagement/tmf-api/partyRoleManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.0.0
