apiVersion: oda.tmforum.org/v1beta2
coreFunction:
  dependantAPIs:
  - apitype: openapi
    id: TMF632
    isRequired: true
    name: PartyManagement
    resources:
    - individual:
      - GET
      - GET /id
    - organization:
      - GET
      - GET /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-PartyManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF669
    isRequired: true
    name: PartyRoleManagement
    resources:
    - PartyRole:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF672
    isRequired: true
    name: UserRolePermissionManagement
    resources:
    - permission:
      - GET
      - GET /id
    - userRole:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRolePermission-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF670
    isRequired: true
    name: PaymentMethodManagement
    resources:
    - paymentMethod:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF670-PaymentMethodManagement/blob/master/TMF670-PaymentMethodManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF676
    isRequired: true
    name: PaymentManagement
    resources:
    - payment:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF676_PaymentManagement/blob/master/TMF676-Payment-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF701
    isRequired: false
    name: ProcessFlowManagement
    resources:
    - processFlow:
      - POST
      - GET
      - GET /id
      - PATCH
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    id: TMF688
    isRequired: false
    name: Event
    resources:
    - event:
      - GET
      - GET /id
    specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
    version: 4.0
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4/docs
    id: TMF666
    implementation: /{{.Release.Name}}-accmngt
    isRequired: true
    name: AccountManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/AccountManagement/v4
    port: 8080
    resources:
    - BillingAccount:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    - BillingCycleSpecification:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    - BillFormat:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    - BillPresentationMedia:
      - GET
      - GET /id
      - POST
      - PATCH /id
      - DELETE /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
    id: TMF701
    implementation: /{{.Release.Name}}-procmngttapi
    isRequired: false
    name: ProcessFlowManagement
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
    port: 8080
    resources:
    - processFlow:
      - GET
      - GET /id
      - POST
      - DELETE /id
    - taskFlow:
      - GET
      - GET /id
      - PATCH /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlowManagement/master/TMF701-ProcessFlowManagement-v4.0.0.swagger.json
    version: 4.0
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
    id: TMF688
    implementation: /{{.Release.Name}}-PromotionManagement
    isRequired: false
    name: Event
    path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
    port: 8080
    resources:
    - listener:
      - POST
    - hub:
      - POST
      - DELETE /id
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF671_Promotion/master/TMF671-Promotion-v4.0.0.swagger.json
    version: 4.0
  publishedEvents:
  - apitype: openapi
    implementation: /{{.Release.Name}}-accmngt
    name: AccountManagement
    port: 80
    resources:
      AccountManagement:
      - billingAccountAttributeValueChangeEvent
      - billingAccountStateChangeEvent
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF666_AccountManagement/master/TMF666-AccountManagement-v4.0.0.swagger.json
  subscribedEvents:
  - apitype: openapi
    name: PartyRoleManagement
    port: 80
    resources:
    - partyRoleCreateEvent
    - partyRoleAttributeValueChangeEvent
    - partyRoleStateChangeEvent
    - partyRoleDeleteEvent
    specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
  - apitype: openapi
    name: UserRolePermissionManagement
    port: 80
    resources:
    - permissionCreateEvent
    - permissionAttributeValueChangeEvent
    - permissionStateChangeEvent
    - permissionDeleteEvent
    - userRoleCreateEvent
    - userRoleAttributeValueChangeEvent
    - userRoleStateChangeEvent
    - userRoleDeleteEvent
    specification: https://github.com/tmforum-apis/TMF672-UserRolePermission/blob/master/TMF672-UserRoleandPermission-v4.0.0.swagger.json
kind: component
managementFunction:
  exposedAPIs:
  - apitype: prometheus
    implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
    name: metrics
    path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
    port: 4000
metadata:
  name: components.oda.tmforum.org
reportingFunction: []
securityFunction:
  controllerRole: '{{ .Values.security.controllerRole }}'
  exposedAPIs:
  - apitype: openapi
    developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
    implementation: '{{.Release.Name}}-partyroleapi'
    name: partyrole
    path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
    port: 8080
    specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
spec:
  componenentDescription: The billing account management component aims to provide
    all the needed functionalities to create, configure and modify billing accounts.
    BAM component has the goal to support and handle the following capabilities/ functionalities.
    Set-up/ creation of Billing account. Associate payment plan(s). Associate payment
    method(s) - optional. Account taxes/ fees exception management. Define account
    associations. Provide account balance details. Set-up Billing contacts. Set-up
    Billing preferences (e.g., bill cycle frequency, invoice media type, invoice template
    option, etc.)
  componentFunctionalBlock: PartyManagement
  componentId: TMFC024
  componentName: BillingaAcountManagement
  componentPublicationDate: 2023-08-18
  componentStatus: specified
  componentVersion: 1.1.0
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  owners:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
