apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      id: TMF648
      name: SalesQuote
      required: true
      resources:
      - quote:
        - GET
        - GET/id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_SalesQuoteManagement/master/TMF648-SalesQuoteManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF663
      name: ShoppingCart
      required: true
      resources:
      - shoppingCart:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF663-ShoppingCartManagement/blob/master/TMF663-ShoppingCartManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF637
      name: ProductInventoryManagement
      required: true
      resources:
      - product:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF637-ProductInventoryManagement/blob/master/TMF637-ProductInventoryManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF620
      name: ProductCatalogManagement
      required: true
      resources:
      - catalog:
        - GET
        - GET /id
      - productOffering:
        - GET
        - GET /id
      - productOfferingPrice:
        - GET
        - GET /id
      - productSpecification:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF620-ProductCatalogManagement/blob/master/TMF620-ProductCatalogManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF645
      name: ServiceQualificationManagement
      required: true
      resources:
      - checkServiceQualification:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF645-ServiceQualificationManagement/blob/master/TMF645-ServiceQualificationManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF622
      name: ProductOrdering
      required: false
      resources:
      - productOrder:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF622-ProductOrdering/blob/master/TMF622-ProductOrdering-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF687
      name: StockManagement
      required: false
      resources:
      - productStock:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF687-StockManagement/blob/master/TMF687-StockManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF699
      name: SalesManagement
      required: false
      resources:
      - sales:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF699-SalesManagement/blob/master/TMF699-SalesManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF632
      name: PartyManagement
      required: false
      resources:
      - individual:
        - GET
        - GET /id
      - organization:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF632-PartyManagement/blob/master/TMF632-PartyManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF651
      name: AgreementManagement
      required: false
      resources:
      - agreement:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF651-AgreementManagement/blob/master/TMF651-AgreementManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF646
      name: AppointmentManagement
      required: false
      resources:
      - appointment:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF646_AppointmentManagement/master/TMF646-Appointment-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF666
      name: AccountManagement
      required: false
      resources:
      - partyAccount:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF666-AccountManagement/blob/master/TMF666-AccountManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF638
      name: ServiceInventoryManagement
      required: false
      resources:
      - service:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF638-ServiceInventoryManagement/blob/master/TMF638-ServiceInventoryManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF639
      name: ResourceInventoryManagement
      required: false
      resources:
      - resource:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF639-ResourceInventoryManagement/blob/master/TMF639-ResourceInventoryManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF669
      name: PartyRoleManagement
      required: false
      resources:
      - partyRole:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF669-PartyRoleManagement/blob/master/TMF669-PartyRoleManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF672
      name: UserRolesPermissions
      required: false
      resources:
      - permission:
        - GET
        - GET /id
      - userRole:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF672-UserRolesandPermissions/blob/master/TMF672-UserRolesandPermissions-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF696
      name: RiskManagement
      required: false
      resources:
      - partyRoleRiskAssessment:
        - GET
        - GET /id
      - productOfferingRiskAssessment:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF696-RiskManagement/blob/master/TMF696-RiskManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF673
      name: GeographicAddressManagement
      required: false
      resources:
      - GeographicAddress:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF673-GeographicAddressManagement/blob/master/TMF673-GeographicAddressManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF674
      name: GeographicSiteManagement
      required: false
      resources:
      - GeographicSite:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF674-GeographicSiteManagement/blob/master/TMF674-GeographicSiteManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF688
      name: Event
      required: false
      resources:
      - event:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      version: 4
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualificationManagement/v4/docs
      id: TMF679
      implementation: /{{.Release.Name}}-pdtquali
      name: ProductOfferingQualification
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductOfferingQualificationManagement/v4
      port: 8080
      required: true
      resources:
      - ProductOfferingQualification:
        - GET
        - GET/id
        - POST
        - PATCH/id
        - DELETE
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF679-ProductOfferingQualificationManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-PromotionManagement
      name: Event
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      port: 8080
      required: false
      resources:
      - listener:
        - POST
      - hub:
        - POST
        - DELETE
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF671-Promotion-v4.0.0.swagger.json
      version: 4
    publishedEvents:
    - apitype: openapi
      implementation: /{{.Release.Name}}-pdtquali
      name: ProductOfferingQualification
      port: 80
      resources:
        ProductOfferingQualification:
        - ProductOfferingQualificationCreateEvent
        - ProductOfferingQualificationAttributeValueChangeEvent
        - ProductOfferingQualificationStateChangeEvent
        - ProductOfferingQualificationDeleteEvent
        - ProductOfferingQualificationInformationRequiredEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF679-ProductOfferingQualification/master/TMF679-ProductOfferingQualification-v4.0.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      name: ProductCatalogManagement
      port: 80
      resources:
        ProductCatalogManagement:
        - CatalogCreateEvent
        - CatalogAttributeValueChangeEvent
        - CatalogStateChangeEvent
        - ProductOfferingCreateEvent
        - ProductOfferingAttributeValueChangeEvent
        - ProductOfferingStateChangeEvent
        - ProductOfferingDeleteEvent
        - ProductOfferingPriceCreateEvent
        - ProductOfferingPriceAttributeValueChangeEvent
        - ProductOfferingPriceStateChangeEvent
        - ProductOfferingPriceDeleteEvent
        - ProductSpecificationCreateEvent
        - ProductSpecificationAttributeValueChangeEvent
        - ProductSpecificationStateChangeEvent
        - ProductSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF622-ProductCatalogManagement/blob/master/TMF622-ProductCatalogManagement-v4.0.0.swagger.json
  description: The Product Configurator ODA Component is empowering sales by offering
    the right product combinations, controlling discounting, and automating approvals
    through support of configuration, pricing and quote generation activities.
  functionalBlock: CoreCommerceManagement
  id: TMFC027
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: ProductConfigurator
  owners:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  publicationDate: 2023-08-18 00:00:00+00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 1.1.0
