component:
  id: tmfc003
  name: tmfc003-productorderdeliveryorchestrationandmanagement
  publicationDate: '2023-08-18T00:00:00.000Z'
images:
  tmf669: tmforumorg/tmfc003-tmf669-v4.0.0:latest
security:
  controllerRole: admin
