apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      id: TMF632
      name: PartyManagement
      required: false
      resources:
      - individual:
        - GET
        - GET/id
      - organization:
        - GET
        - GET/id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF632_PartyManagement/master/TMF632-Party-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF669
      name: PartyRoleManagement
      required: false
      resources:
      - PartyRoleManagement:
        - GET
        - GET/id
      specification: https://github.com/tmforum-apis/TMF669_PartyRole/blob/master/TMF669-PartyRole-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF620
      name: ProductCatalogManagement
      required: false
      resources:
      - productOffering:
        - GET
        - GET/id
      - productOfferingPrice:
        - GET
        - GET/id
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF651
      name: AgreementManagement
      required: false
      resources:
      - agreement:
        - GET
        - GET/id
      - agreementSpecification:
        - GET
        - GET/id
      specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF648
      name: QuoteManagement
      required: false
      resources:
      - Quote:
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF688
      name: Event
      required: false
      resources:
      - event:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF688-Event/blob/master/TMF688-Event-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF622
      name: ProductOrder
      required: false
      resources:
      - ProductOrder:
        - GET
        - GET /id
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/master/TMF622-ProductOrder-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      id: TMF701
      name: ProcessFlowManagement
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.1.0.swagger.json
      version: 4
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4/docs
      id: TMF699
      implementation: /{{.Release.Name}}-SalesManagement
      name: SalesManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/v4
      port: 8080
      required: true
      resources:
      - SalesLead:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      - SalesOpportunity:
        - GET
        - GET /id
        - POST
        - PATCH
        - DELETE
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF699-Sales-v4.0.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4/docs
      id: TMF701
      implementation: /{{.Release.Name}}-ProcessFlowManagement
      name: ProcessFlowManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/v4
      port: 8080
      required: false
      resources:
      - processFlow:
        - POST
        - GET
        - GET /id
        - DELETE
      - taskFlow:
        - PATCH
        - GET
        - GET /id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF701-ProcessFlow-v4.1.0.swagger.json
      version: 4
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-PromotionManagement
      name: Event
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PromotionManagement/v4
      port: 8080
      required: false
      resources:
      - listener:
        - POST
      - hub:
        - POST
        - DELETE
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF671-Promotion-v4.1.0.swagger.json
      version: 4
    publishedEvents:
    - -resources:
        SalesLead:
        - SalesLeadCreateEvent
        - SalesLeadAttributeValueChangeEvent
        - SalesLeadStateChangeEvent
        - SalesLeadDeleteEvent
        SalesOpportunity:
        - SalesOpportunityCreateEvent
        - SalesOpportunityAttributeValueChangeEvent
        - SalesOpportunityStateChangeEvent
        - SalesOpportunityDeleteEvent
      apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/SalesManagement/hub
      implementation: /{{.Release.Name}}-SalesManagement
      name: SalesManagement
      port: 80
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF699_SalesManagement/master/TMF699-SalesManagement-v4.0.0.swagger.json
    - -resources:
        ProcessFlowManagement:
        - processFlowCreateEvent
        - processFlowStateChangeEvent
        - processFlowStateDeleteEvent
        - processFlowStateAttributeValueChangeEvent
        - processFlowSpecificationAttributeValueChangeEvent
        - processFlowSpecificationCreateEvent
        - processFlowSpecificationDeleteEvent
        - processFlowSpecificationStateChangeEvent
        - taskFlowCreateEvent
        - taskFlowStateChangeEvent
        - taskFlowDeleteEvent
        - taskFlowAttributeValueChangeEvent
        - taskFlowInformationRequiredEvent
        - taskFlowSpecificationAttributeValueChangeEvent
        - taskFlowSpecificationCreateEvent
        - taskFlowSpecificationDeleteEvent
        - taskFlowSpecificationStateChangeEvent
      apitype: openapi
      hub: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProcessFlowManagement/hub
      implementation: /{{.Release.Name}}-ProcessFlowManagementEvent
      name: ProcessFlowManagement
      port: 80
      specification: https://github.com/tmforum-apis/TMF701_ProcessFlow/blob/master/TMF701-ProcessFlow-v4.1.0.swagger.json
    subscribedEvents:
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyManagement/call-back
      implementation: /{{.Release.Name}}-PartyManagement
      name: PartyManagement
      port: 80
      resources:
      - Individual:
        - IndividualCreateEvent
        - IndividualAttributeValueChangeEvent
        - IndividualStateChangeEvent
        - IndividualDeleteEvent
      - Organization:
        - OrganizationCreateEvent
        - OrganizationAttributeValueChangeEvent
        - OrganizationStateChangeEvent
        - OrganizationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF632_PartyManagement/blob/master/TMF632-Party-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
      implementation: /{{.Release.Name}}-ProductCatalogManagement
      name: ProductCatalogManagement
      port: 80
      resources:
      - ProductOffering:
        - ProductOfferingCreateEvent
        - ProductOfferingAttributeValueChangeEvent
        - ProductOfferingStateChangeEvent
        - ProductOfferingDeleteEvent
      - ProductSpecification:
        - ProductSpecificationCreateEvent
        - ProductSpecificationAttributeValueChangeEvent
        - ProductSpecificationStateChangeEvent
        - ProductSpecificationDeleteEvent
      - ProductOfferingPrice:
        - ProductOfferingPriceCreateEvent
        - ProductOfferingPriceAttributeValueChangeEvent
        - ProductOfferingPriceStateChangeEvent
        - ProductOfferingPriceDeleteEvent
      specification: https://github.com/tmforum-apis/TMF620_ProductCatalog/blob/master/TMF620-ProductCatalog-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/ProductCatalogManagement/call-back
      implementation: /{{.Release.Name}}-ProductOrder
      name: ProductOrder
      port: 80
      resources:
      - ProductOrder:
        - ProductOrderCreateEvent
        - ProductOrderAttributeValueChangeEvent
        - ProductOrderDeleteEvent
        - ProductOrderStateChangeEvent
        - ProductOrderInformationRequiredEvent
      specification: https://github.com/tmforum-apis/TMF622_ProductOrder/blob/ProductOrder/TMF622-ProductOrder-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/Agreement/call-back
      implementation: /{{.Release.Name}}-Agreement
      name: AgreementManagement
      port: 80
      resources:
      - Agreement:
        - AgreementCreateEvent
        - AgreementAttributeValueChangeEvent
        - AgreementStateChangeEvent
        - AgreementDeleteEvent
      - AgreementSpecification:
        - AgreementSpecificationCreateEvent
        - AgreementSpecificationAttributeValueChangeEvent
        - AgreementSpecificationStateChangeEvent
        - AgreementSpecificationDeleteEvent
      specification: https://github.com/tmforum-apis/TMF651_AgreementManagement/blob/master/TMF651-Agreement-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/QuoteManagement/call-back
      implementation: /{{.Release.Name}}-QuoteManagement
      name: QuoteManagement
      port: 80
      resources:
      - Quote:
        - QuoteCreateEvent
        - QuoteStateChangeEvent
        - QuoteDeleteEvent
        - QuoteInformationRequiredEvent
        - QuoteAttributeValueChangeEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF648_QuoteManagement/master/TMF648-QuoteManagement-v4.0.0.swagger.json
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/PartyRoleManagement/call-back
      implementation: /{{.Release.Name}}-PartyRoleManagement
      name: PartyRoleManagement
      port: 80
      resources:
      - PartyRole:
        - PartyRoleCreateEvent
        - PartyRoleAttributeValueChangeEvent
        - PartyRoleStateChangeEvent
        - PartyRoleDeleteEvent
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF701_ProcessFlow/master/TMF701-ProcessFlow-v4.1.0.swagger.json
  description: 'Lead and Opportunity Management provides the necessary functionality
    during pre-sales stage in terms of: lead and opportunity capture, qualification,
    reporting, support.'
  functionalBlock: PartyManagement
  id: TMFC036
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: LeadAndOpportunityManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: 2023-08-18 00:00:00+00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 1.1.0
