---
# Source: tmfc036-leadandopportunitymanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc036-leadandopportunitymanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-sales-management-api'
spec:
  ports:
  - name: tcp-release-name-sales-m
    port: 8080
    targetPort: 'release-name-sales-m'
  selector:
    impl: 'release-name-sales-management-api'
---
# Source: tmfc036-leadandopportunitymanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-party-role-management-api'
spec:
  ports:
  - name: tcp-release-name-party-r
    port: 8080
    targetPort: 'release-name-party-r'
  selector:
    impl: 'release-name-party-role-management-api'
---
# Source: tmfc036-leadandopportunitymanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc036-leadandopportunitymanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-sales-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-sales-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc036-leadandopportunitymanagement'
        impl: 'release-name-sales-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc036-leadandopportunitymanagement'
        image: 'tmforumorg/tmfc036-tmf699-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-sales-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-sales-m'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc036-leadandopportunitymanagement/tmf-api/sales/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc036-leadandopportunitymanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-party-role-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-party-role-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc036-leadandopportunitymanagement'
        impl: 'release-name-party-role-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc036-leadandopportunitymanagement'
        image: 'tmforumorg/tmfc036-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-party-role-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-party-r'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc036-leadandopportunitymanagement/tmf-api/partyRoleManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc036-leadandopportunitymanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc036-leadandopportunitymanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc036-leadandopportunitymanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc036-leadandopportunitymanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc036-leadandopportunitymanagement'
  name: 'release-name-tmfc036-leadandopportunitymanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: party-role-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: product-catalog-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF620_Product_Catalog/4.1.0/swagger/TMF620_Product_Catalog_Management_API_v4.1.0_swagger.json
    - apitype: openapi
      name: agreement-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF651_Agreement/4.0.0/swagger/TMF651_Agreement_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: quote-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF648_Quote/4.0.0/swagger/TMF648_Quote_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      name: product-ordering-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF622_Product_Ordering/4.0.0/swagger/TMF622_Product_Ordering_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-sales-management-api'
      name: sales-management-api
      path: /release-name-tmfc036-leadandopportunitymanagement/tmf-api/sales/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF699_Sales/4.0.0/swagger/TMF699_Sales_Management_API_v4.0.0_swagger.json
  description: 'Lead and Opportunity Management provides the necessary functionality
    during pre-sales stage in terms of: lead and opportunity capture, qualification,
    reporting, support.'
  functionalBlock: PartyManagement
  id: TMFC036
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: 'release-name-tmfc036-leadandopportunitymanagement-sm'
      name: metrics
      path: /release-name-tmfc036-leadandopportunitymanagement/metrics
      port: 4000
  name: LeadAndOpportunityManagement
  owners:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-party-role-management-api'
      name: party-role-management-api
      path: /release-name-tmfc036-leadandopportunitymanagement/tmf-api/partyRoleManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.0
