apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  name: components.oda.tmforum.org
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      id: TMF688
      name: EventManagement
      required: false
      resources:
      - hub:
        - GET
        - POST
        - GET /id
        - DELETE /id
      specification: https://github.com/tmforum-apis/TMF688-EventManagement/blob/master/TMF688-EventManagement-v4.0.0.swagger.json
      version: 4
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4/docs
      id: TMF688
      implementation: /{{.Release.Name}}-EventManagement
      name: EventManagement
      path: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/v4
      port: 8080
      required: true
      resources:
      - topic:
        - GET
        - POST
        - GET /id
        - PATCH /id
        - DELETE /id
      - topic/id/event:
        - POST
      - topic/id/queryStore:
        - GET
      - topic/id/hub:
        - GET
        - POST
        - GET /id
        - PATCH /id
        - DELETE /id
      - topic/id/importJob:
        - GET
        - POST
        - GET /id
        - PATCH /id
        - DELETE /id
      - topic/id/exportJob:
        - GET
        - POST
        - GET /id
        - PATCH /id
        - DELETE /id
      specification: https://tmforum-rand.github.io/TMForum-ODA-Asset-Build/swaggers/TMF688-EventManagement-v4.0.0.swagger.json
      version: 4
    publishedEvents:
    - apitype: openapi
      call-back: /{{.Release.Name}}-{{.Values.component.type}}/tmf-api/EventManagement/call-back
      implementation: /{{.Release.Name}}-EventManagement
      name: EventManagement
      port: 80
      resources:
      - EventManagement:
        - topicCreateEvent
        - TopicAttributeValueChangeEvent
        - TopicStateChangeEvent
        - TopicDeleteEvent
        - HubCreateEvent
        - HubAttributeValueChangeEvent
        - HubStateChangeEvent
        - HubDeleteEvent
      specification: https://github.com/tmforum-apis/TMF688-EventManagement/blob/master/TMF688-EventManagement-v4.0.0.swagger.json
    subscribedEvents: []
  description: Event Management component is a messaging management component that
    is responsible for processing events as they happen from components. Processing
    of record of activities include modelling event messages, syntax validation and
    formatting of event messages and sending/receiving messages between components
    (consumer/producer). Event Management component supports different patterns of
    usage, including Event notification (subscription), Event-sourcing (representational
    state changes) and Event-carried state transfer (including data needed to perform
    further processing). Event Management component should include functionality providing
    a centralised CQRS queryStore for all components that implement event-sourcing
    with event carrier state transfer.
  functionalBlock: DecouplingAndIntegration
  id: TMFC019
  maintainers:
  - email: gaetano.biancardi@accenture.com
    name: Gaetano Biancardi
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: '{{.Release.Name}}-{{.Values.component.name}}-sm'
      name: metrics
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000
  name: EventManagement
  owners:
  - email: koen.peeters@ciminko.lu
    name: Loen Peeters
  publicationDate: 2023-08-18 00:00:00+00:00
  securityFunction:
    controllerRole: '{{ .Values.security.controllerRole }}'
    exposedAPIs:
    - apitype: openapi
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      id: TMF669
      implementation: '{{.Release.Name}}-partyroleapi'
      name: partyrole
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      port: 8080
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
  status: specified
  version: 1.1.1
