---
# Source: tmfc035-permissionsmanagement/templates/PersistentVolumeClaim-0.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-mongodb-pv-claim'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Source: tmfc035-permissionsmanagement/templates/Service-0.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-user-role-permission-management-api'
spec:
  ports:
  - name: tcp-release-name-user-ro
    port: 8080
    targetPort: 'release-name-user-ro'
  selector:
    impl: 'release-name-user-role-permission-management-api'
---
# Source: tmfc035-permissionsmanagement/templates/Service-1.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-party-role-management-api'
spec:
  ports:
  - name: tcp-release-name-party-r
    port: 8080
    targetPort: 'release-name-party-r'
  selector:
    impl: 'release-name-party-role-management-api'
---
# Source: tmfc035-permissionsmanagement/templates/Service-2.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-party-role-management-api'
spec:
  ports:
  - name: tcp-release-name-party-r
    port: 8080
    targetPort: 'release-name-party-r'
  selector:
    impl: 'release-name-party-role-management-api'
---
# Source: tmfc035-permissionsmanagement/templates/Service-3.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-mongodb'
spec:
  ports:
  - name: tcp-release-name-mongodb
    port: 27017
    targetPort: 'release-name-mongodb'
  selector:
    impl: 'release-name-mongodb'
---
# Source: tmfc035-permissionsmanagement/templates/Deployment-0.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-user-role-permission-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-user-role-permission-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc035-permissionsmanagement'
        impl: 'release-name-user-role-permission-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc035-permissionsmanagement'
        image: 'tmforumorg/tmfc035-tmf672-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-user-role-permission-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-user-ro'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc035-permissionsmanagement/rolesAndPermissions/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc035-permissionsmanagement/templates/Deployment-1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-party-role-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-party-role-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc035-permissionsmanagement'
        impl: 'release-name-party-role-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc035-permissionsmanagement'
        image: 'tmforumorg/tmfc035-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-party-role-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-party-r'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc035-permissionsmanagement/tmf-api/partyRoleManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc035-permissionsmanagement/templates/Deployment-2.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-party-role-management-api'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-party-role-management-api'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc035-permissionsmanagement'
        impl: 'release-name-party-role-management-api'
        version: v4.0.0
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc035-permissionsmanagement'
        image: 'tmforumorg/tmfc035-tmf669-v4.0.0:latest'
        imagePullPolicy: Always
        name: 'release-name-party-role-management-api'
        ports:
        - containerPort: 8080
          name: 'release-name-party-r'
        resources:
          limits:
            cpu: '0.5'
            memory: 900Mi
          requests:
            cpu: '0.1'
            memory: 600Mi
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /release-name-tmfc035-permissionsmanagement/tmf-api/partyRoleManagement/v4/
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
---
# Source: tmfc035-permissionsmanagement/templates/Deployment-3.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-mongodb'
spec:
  replicas: 1
  selector:
    matchLabels:
      impl: 'release-name-mongodb'
  template:
    metadata:
      labels:
        app: 'release-name-tmfc035-permissionsmanagement'
        impl: 'release-name-mongodb'
        version: mongo-5.0.1
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
          value: 'release-name-mongodb'
        - name: RELEASE_NAME
          value: 'release-name'
        - name: COMPONENT_NAME
          value: 'release-name-tmfc035-permissionsmanagement'
        image: mongo:5.0.1
        imagePullPolicy: Always
        name: 'release-name-mongodb'
        ports:
        - containerPort: 27017
          name: 'release-name-mongodb'
        volumeMounts:
        - mountPath: /data/db
          name: 'release-name-mongodb-pv-storage'
      volumes:
      - name: 'release-name-mongodb-pv-storage'
        persistentVolumeClaim:
          claimName: 'release-name-mongodb-pv-claim'
---
# Source: tmfc035-permissionsmanagement/templates/component-0.yaml
apiVersion: oda.tmforum.org/v1beta2
kind: component
metadata:
  labels:
    oda.tmforum.org/componentName: 'release-name-tmfc035-permissionsmanagement'
  name: 'release-name-tmfc035-permissionsmanagement'
spec:
  coreFunction:
    dependentAPIs:
    - apitype: openapi
      name: party-management-api
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF632_Party/4.0.0/swagger/TMF632_Party_Management_API_v4.0.0_swagger.json
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-user-role-permission-management-api'
      name: user-role-permission-management-api
      path: /release-name-tmfc035-permissionsmanagement/rolesAndPermissions/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF672_User_Role_Permission/4.0.0/swagger/TMF672_User_Role_Permission_Management_API_v4.0.0_swagger.json
    - apitype: openapi
      implementation: 'release-name-party-role-management-api'
      name: party-role-management-api
      path: /release-name-tmfc035-permissionsmanagement/tmf-api/partyRoleManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  description: 'Party Roles & Permissions Management component aims to manage and
    expose, roles and related permissions. Permissions Management component allows
    to: create, modify and delete permissions. delegate permissions. When a specific
    role is assigned, a set of permissions is inherited.'
  functionalBlock: PartyManagement
  id: TMFC035
  maintainers:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  managementFunction:
    exposedAPIs:
    - apitype: prometheus
      implementation: 'release-name-tmfc035-permissionsmanagement-sm'
      name: metrics
      path: /release-name-tmfc035-permissionsmanagement/metrics
      port: 4000
  name: PermissionsManagement
  owners:
  - email: matteo.destino@accenture.com
    name: Matteo Destino
  publicationDate: '2023-08-18T00:00:00.000Z'
  securityFunction:
    controllerRole: 'admin'
    exposedAPIs:
    - apitype: openapi
      implementation: 'release-name-party-role-management-api'
      name: party-role-management-api
      path: /release-name-tmfc035-permissionsmanagement/tmf-api/partyRoleManagement/v4/
      port: 8080
      specification: https://tmf-open-api-table-documents.s3.eu-west-1.amazonaws.com/OpenApiTable/TMF669_Party_Role/4.0.0/swagger/TMF669_Party_Role_Management_API_v4.0.0_swagger.json
  status: specified
  version: 1.1.1
